---
title: "Appendix:  Simulation details and code"
author: "Yenny Webb-Vargas"
output:
  html_document: default
  pdf_document:
    keep_tex: yes
---

This is the online companion to the paper ['An Imputation-Based Solution to Using Mismeasured Covariates in Propensity Score Analysis'](http://biostats.bepress.com/jhubiostat/paper269/), by Yenny Webb-Vargas, Kara Rudolph, David Lenis, Peter Murakami, and Elizabeth Stuart. 

You can see the details of the simulations, color figures and code by following the links:

Normal scenario: 

* [Normal 'Y', normal (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_normal_XZW_normal/)
* [Normal 'Y', normal (X,Z,W), including a simple imputation method](http://ywebbvar.github.io/PS_MIEC/Simulations/Simple_imputation/)
* [Normal 'Y', normal (X,Z,W), with varying sample sizes for calibration and main data sets](http://ywebbvar.github.io/PS_MIEC/Simulations/Sample_sizes/)
* [Normal 'Y', normal (X,Z,W), estimating Average Treatment effect on the Treated (ATT)](http://ywebbvar.github.io/PS_MIEC/Simulations/ATT/)

Non-normal scenarios:

* [Normal 'Y', mixture (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_normal_XZW_mixture/)
* [Bernoulli 'Y', normal (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_bernoulli_XZW_normal/)
* [Bernoulli 'Y', mixture (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_bernoulli_XZW_mixture/)
* [Mixture 'Y', normal (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_mixture_XZW_normal/)
* [Mixture 'Y', mixture (X,Z,W)](http://ywebbvar.github.io/PS_MIEC/Simulations/Y_mixture_XZW_mixture/)
* [Normal 'Y', normal (X,Z,W), where Z is a binary variable](http://ywebbvar.github.io/PS_MIEC/Simulations/CategoricalZ/)

You can see the [code for Guo, Little and McConnell's Multiple Imputation for External Calibration](http://ywebbvar.github.io/PS_MIEC/MIEC_original/), or download [the R script](http://ywebbvar.github.io/PS_MIEC/MIEC_original/MI-EC_algorithm.r)  we used in the simulations.